apply plugin: 'com.android.application'

android {
    namespace 'rahook.app'
    compileSdk 34
    defaultConfig {
        applicationId "rahook.app"
        minSdk 21
        targetSdk 34
        ndkVersion '25.1.8937393'
        ndk { abiFilters 'x86_64', 'x86' }
        externalNativeBuild {
            cmake { cppFlags "-std=gnu11" }
        }
    }
    externalNativeBuild {
        cmake { path "CMakeLists.txt" }
    }
}
